# Reverse proxy, the actual, exposed endpoint
nginx:
  image: nginx
  container_name: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /etc/nginx/certs:/etc/nginx/certs:ro
    - /etc/nginx/conf.d
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
  restart: always

# Automated generation of the proxy's config
nginx-gen:
  image: jwilder/docker-gen
  container_name: nginx-gen
  volumes_from:
    - nginx
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
  command:
      -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  restart: always

# Automated renewal of https certs
letsencrypt:
  image: jrcs/letsencrypt-nginx-proxy-companion
  container_name: letsencrypt
  environment:
    - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
  volumes_from:
    - nginx
  volumes:
    - /etc/nginx/certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
  restart: always

# Sample web server, replace env vars!!!
web:
  image: nginx
  container_name: web
  environment:
    - VIRTUAL_HOST=purpletentacle.rocks
    - LETSENCRYPT_HOST=purpletentacle.rocks
    - LETSENCRYPT_EMAIL=info@purpletentacle.rocks
  volumes:
    - ./public:/usr/share/nginx/html:ro
  restart: always

# cdn
web:
  image: nginx
  container_name: web
  environment:
    - VIRTUAL_HOST=cdn.purpletentacle.rocks
    - LETSENCRYPT_HOST=cdn.purpletentacle.rocks
    - LETSENCRYPT_EMAIL=info@purpletentacle.rocks
  volumes:
    - ../cdn:/usr/share/nginx/html:ro
  restart: always

# Registry
registry:
  restart: always
  image: registry:2
  env_file: ../registry.env
  environment:
    - VIRTUAL_HOST=registry.purpletentacle.rocks
    - VIRTUAL_PORT=5000
    - LETSENCRYPT_HOST=registry.purpletentacle.rocks
    - LETSENCRYPT_EMAIL=info@purpletentacle.rocks
  volumes:
    - ../registry/public:/var/lib/registry
    # - /etc/nginx/certs:/certs
    - ../registry/auth:/auth
